from typing import Protocol, runtime_checkable, Optional


@runtime_checkable
class ACUnitPort(Protocol):
    device_id: str

    async def refresh(self) -> None: ...
    async def turn_on(self) -> None: ...
    async def turn_off(self) -> None: ...

    def is_online(self) -> bool: ...
    def get_display_temperature(self) -> float: ...
    def get_target_temperature(self) -> float: ...
    async def set_target_temperature(self, temp: float) -> None: ...

    def get_economy_mode(self) -> bool: ...
    async def set_economy_mode(self, mode: bool) -> None: ...

    def get_powerful_mode(self) -> bool: ...
    async def set_powerful_mode(self, mode: bool) -> None: ...

    def get_outdoor_low_noise(self) -> bool: ...
    async def set_outdoor_low_noise(self, mode: bool) -> None: ...

    def get_operating_mode(self) -> str: ...         # np. "COOL", "HEAT", ...
    async def set_operation_mode(self, mode: int) -> None: ...
