
from typing import Protocol

class WaterHeaterPort(Protocol):
    async def refresh(self) -> None: ...
    async def set_power(self, on: bool) -> None: ...
    def get_power(self) -> bool: ...

    async def set_target_temperature(self, temp_c: float) -> None: ...
    def get_target_temperature(self) -> float: ...

    def get_mode_text(self) -> str: ...
    def get_current_temperature(self) -> float: ...

    async def set_operation_mode(self, mode: int) -> None: ...
